default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false
    )
  end

  desc "Sync certificates and profiles"
  lane :certificates do
    match(type: "appstore", readonly: is_ci)
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"] || Time.now.to_i.to_s,
      xcodeproj: "meetup-ios.xcodeproj"
    )
    build_app(
      project: "meetup-ios.xcodeproj",
      scheme: "meetup-ios",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "gautamlgtm.meetup-ios" => "match AppStore gautamlgtm.meetup-ios"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
