default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
  end

  desc "Sync certificates and profiles"
  lane :certificates do
    match(type: "appstore", readonly: is_ci)
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "meetup-ios.xcodeproj"
    )
    build_app(
      project: "meetup-ios.xcodeproj",
      scheme: "meetup-ios",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "gautamlgtm.meetup-ios" => "match AppStore gautamlgtm.meetup-ios"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
