ALTER TABLE public.receipts
  ADD COLUMN IF NOT EXISTS tax       DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tip       DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS surcharge DECIMAL(10,2) NOT NULL DEFAULT 0;
